// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TodoList$Type } from "./TodoList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TodoList"]: TodoList$Type;
    ["hardhat/contracts/TodoList.sol:TodoList"]: TodoList$Type;
  }

  interface ContractTypesMap {
    ["TodoList"]: GetContractReturnType<TodoList$Type["abi"]>;
    ["hardhat/contracts/TodoList.sol:TodoList"]: GetContractReturnType<TodoList$Type["abi"]>;
  }
}
